stages:
- stage: 'Convert_Bower_to_NPM'
  jobs:
    - job: convert
      steps:
      - task: CmdLine@2
        displayName: 'Install Bower and run bower-away'
        inputs:
          script: |
            # Ensure Bower is installed
            npm install -g bower
            
            # Convert bower.json to package.json using bower-away
            npx bower-away

      - task: CmdLine@2
        displayName: 'Pull latest changes'
        inputs:
          script: |
            # Pull the latest changes from the master branch
            git pull origin master

      - task: CmdLine@2
        displayName: 'Commit and Push package.json'
        inputs:
          script: |
            # Add the newly generated package.json file to Git
            git add package.json
            
            # Commit the change with a message
            git commit -m "Convert bower.json to package.json"

            # Push the changes to the master branch
            git push origin HEAD:master
