stages:
- stage: 'Convert_Bower_to_NPM'
  jobs:
    - job: convert
      steps:
      - task: CmdLine@2
        displayName: 'Install Bower and run bower-away'
        inputs:
          script: |
            # Ensure Bower is installed
            npm install -g bower
            
            # Convert bower.json to package.json using bower-away
            npx bower-away

            # List files to verify package.json was created
            ls -la

      - task: CmdLine@2
        displayName: 'Configure Git'
        inputs:
          script: |
            # Configure Git user
            git config user.email "andrei_popa11@yahoo.com"
            git config user.name "popaandrei11"

            # Set Git credentials for pushing
            git config --global credential.helper store
            echo "https://<your-token>:x-oauth-basic@github.com" > ~/.git-credentials

      - task: CmdLine@2
        displayName: 'Checkout master branch'
        inputs:
          script: |
            # Check out master branch
            git checkout master

      - task: CmdLine@2
        displayName: 'Pull latest changes'
        inputs:
          script: |
            # Pull the latest changes from the master branch
            git pull origin master

      - task: CmdLine@2
        displayName: 'Commit and Push package.json'
        inputs:
          script: |
            # Verify package.json exists
            ls -la

            # Add the newly generated package.json file to Git
            git add package.json
            
            # Commit the change with a message
            git commit -m "Convert bower.json to package.json"

            # Push the changes to the master branch
            git push origin master
