stages:
- stage: 'BlackDuck_Scan'
  jobs:
    - job: detect
      steps:
      - task: CmdLine@2
        displayName: 'Install npm dependencies'
        inputs:
          script: |
            find . -name "bower.json" -type f -print0 |
            xargs -0 -I {} sh -c 'dir=$(dirname "$1"); cd "$dir" && npm install --lockfile-version 3 --package-lock-only --force || echo "Failed to generate package-lock.json in $dir"' sh {}

      # Add a step to commit the changes
      - task: CmdLine@2
        displayName: 'Commit package-lock.json files'
        inputs:
          script: |
            git add **/package-lock.json
            git commit -m "Add or update package-lock.json files"

      # Add a step to push the changes back to the repository
      - task: CmdLine@2
        displayName: 'Push changes'
        inputs:
          script: |
            git push origin HEAD:master
      
      - task: SynopsysDetectTask@9
        displayName: 'Run Synopsys Detect'
        inputs:
          BlackDuckService: 'BlackDuck'
          DetectArguments: |
            --detect.project.name=npm-bower
            --detect.project.version.name=1
            --blackduck.trust.cert=true  
            --detect.detector.search.depth=100  
            --detect.tools=DETECTOR  
            --detect.detector.search.continue=true
            --detect.code.location.name=npm-bower-1
          DetectVersion: 'latest'
