stages:
- stage: 'Transform_Bower_to_NPM'
  jobs:
    - job: transform
      steps:
      - task: CmdLine@2
        displayName: 'Install Bower and run bower-away'
        inputs:
          script: |
            # Ensure Bower is installed
            npm install -g bower
            
            # Install bower-away (it's safe to use npx directly)
            npx bower-away

      - task: CmdLine@2
        displayName: 'Generate package-lock.json'
        inputs:
          script: |
            # Generate package-lock.json with lockfile version 3
            npm install --lockfile-version 3 --package-lock-only --force

      - task: CmdLine@2
        displayName: 'Configure Git'
        inputs:
          script: |
            git config user.email "your-email@example.com"
            git config user.name "Your Name"

      - task: CmdLine@2
        displayName: 'Pull latest changes'
        inputs:
          script: |
            git pull origin master

      - task: CmdLine@2
        displayName: 'Commit package.json and package-lock.json'
        inputs:
          script: |
            git add package.json package-lock.json
            git commit -m "Transform bower.json to package.json and generate package-lock.json"

      - task: CmdLine@2
        displayName: 'Push changes'
        inputs:
          script: |
            git push origin HEAD:master
